anoideaopen/foundation

hlfcreator/creator.go

ToDo added

---

core/auth.go
mock/wallet.go
test/integration/cmn/client/user.go

secp256k1 key should sign sha256 of the initial message

signing sha256 message with secp256k1 key

---

.github/workflows/go.yml
core/cc_core_init_invoke.go
core/predict_acl_invoke.go
core/task_executor.go
mock/task_executor.go
test/integration/batcher-only-tx/batcher_suit_test.go
test/integration/batcher-only-tx/batcher_test.go
test/integration/cmn/client/task_executor.go

- added integration tests grou "batcher-only-tx" for method executeTasks:
- batch: healthCheckNb
- batch: healthCheck
-  batch: healthCheckNb, healthCheck
- emit
- added validation execute task exec by robot sdk client

added task executor integration test

---

test/integration/channel-transfer-only-tx/channel_transfer_suit_test.go
test/integration/channel-transfer-only-tx/channel_transfer_test.go
test/integration/channel-transfer/channel_transfer_suit_test.go
test/integration/channel-transfer/channel_transfer_test.go

Channel transfer tests migrated to testSuite usage

Channel transfer tests migrated to testSuite usage

---

.github/workflows/go.yml
core/task_executor.go
test/integration/batcher-only-tx/batcher_suit_test.go
test/integration/batcher-only-tx/batcher_test.go
test/integration/channel-transfer-batcher-only-tx/channel_transfer_batcher_suit_test.go
test/integration/channel-transfer-batcher-only-tx/channel_transfer_batcher_test.go
test/integration/cmn/client/interfaces.go
test/integration/cmn/client/task_executor.go
test/integration/cmn/client/testsuit.go

- Batcher tests updated with using TestSuite.
- New test for channel transfer with batcher added.
- TestSuite extended with execute tasks methods.

Updated batcher tests; added channel transfer with batcher test

---

test/integration/swap/swap_suit_test.go
test/integration/swap/swaps_test.go

Swap tests migrated to testSuite usage

Swap tests migrated to testSuite usage

---

test/integration/version-and-nonce/version_and_nonce_test.go
test/integration/version-and-nonce/version_nonce_suit_test.go

Version and nonce tests migrated to testSuite usage

Version and nonce tests migrated to testSuite usage

---

.github/workflows/go.yml
test/integration/general/general_test.go
test/integration/multisigned-user/msu_suit_test.go
test/integration/multisigned-user/msu_test.go

General & multisigned user tests migrated to testSuite usage

General & multisigned user tests migrated to testSuite usage

---

test/integration/cmn/client/nw_options.go
test/integration/cmn/client/testsuit.go
test/integration/cmn/network.go
test/integration/cmn/nwf_options.go

common config options added

---

core/acl/accessmatrix.go
core/acl/common.go
mock/mock_acl.go
mock/wallet_accessmatrix.go
test/integration/channel-transfer-multi/channel_transfer_multi_test.go
test/integration/channel-transfer/channel_transfer_test.go
test/integration/cmn/client/acl.go
test/integration/cmn/client/interfaces.go
test/integration/cmn/client/invoke.go
test/integration/cmn/client/multisigned_user.go
test/integration/cmn/client/query.go
test/integration/cmn/client/task_executor.go
test/integration/cmn/client/testsuit.go
test/integration/version-and-nonce/version_nonce_suit_test.go
test/unit/accessmatrix_test.go

External test suite & nominee methods

External test suite

---

core/bc_chtransfer.go
core/cc_core.go
core/cc_core_init_invoke.go
test/integration/channel-transfer-only-tx/channel_transfer_test.go
test/integration/channel-transfer-task-executor-only-tx/channel_transfer_task_executor_test.go
test/unit/chtransfer_test.go
token/methods_test.go

add batch method removeCCTransferTo and
deleteCCTransferFrom is depricated

add batch method removeCCTransferTo

---

core/cachestub/tx_cache_stub_test.go

tx cache stub test modified

---

core/cc_batch_test.go
mocks/helpers.go

Cc batch test

---

core/cc_batch_test.go
mocks/helpers.go
test/unit/accounting_test.go

Accounting test migrated to ChaincodeStub usage

Accounting test

---

core/telemetry/trace_provider.go

Fixing version of telemetry schema in imports

fix telemetry version

---

core/balance/type.go
core/cc_batch.go
mocks/acl.go
mocks/helpers.go
mocks/multisigned_user.go
mocks/user.go
test/integration/basic/basic_key_types_test.go
test/integration/basic/basic_test.go
test/integration/channel-transfer-multi/channel_transfer_multi_test.go
test/integration/channel-transfer-only-tx/channel_transfer_test.go
test/integration/channel-transfer-task-executor-only-tx/channel_transfer_task_executor_test.go
test/integration/channel-transfer/channel_transfer_test.go
test/integration/cmn/client/acl.go
test/integration/cmn/client/interfaces.go
test/integration/cmn/client/invoke.go
test/integration/cmn/client/query.go
test/integration/cmn/client/task_executor.go
test/integration/cmn/client/testsuit.go
test/integration/general/general_test.go
test/integration/multisigned-user/msu_test.go
test/integration/swap/swaps_test.go
test/integration/task_executor_only_tx/task_executor_test.go
test/integration/version-and-nonce/version_and_nonce_test.go
test/unit/indexer_test.go
test/unit/tokens_test.go

Indexer test migrated to mock stub usage

Indexer test

---

mock/grpc/mock_client_conn.go
mock/ledger.go
mock/mock_acl.go
mock/multisig.go
mock/stub/mock_stub.go
mock/task_executor.go
mock/tracing.go
mock/wallet.go
mock/wallet_accessmatrix.go

Old methods marked as deprecated

Old methods marked as deprecated

---

test/unit/config_base_test.go
test/unit/indexer_test.go

config base test migrated to ChaincodeStub usage

config base test migrated to ChaincodeStub usage

---

test/unit/base_contract_test.go

Base contract test modified to matrix tests

Base contract test modified to matrix tests

---

test/unit/base_contract_test.go

base contract test migrated to MockStub usage

base contract test migrated to MockStub usage

---

mocks/certs.go
mocks/helpers.go
mocks/mockstub/mock_stub.go
test/unit/config_base_test.go

config base test migrated to MockStub usage

config base test migrated to MockStub usage

---

test/unit/external_transfers_test.go

External transfer test migrated to MockStub usage

External transfer test

---

test/unit/chtransfer_test.go
test/unit/industrial_balances_test.go

industrial balances test migrated to MockStub usage

industrial balances test migrated to MockStub usage

---

mock/ledger.go
mocks/mockstub/mock_stub.go
test/unit/base_contract_test.go
test/unit/common_test.go
test/unit/multiswap_test.go
test/unit/tokens_test.go
token/buy_buyback.go
token/buy_buyback_test.go
token/errors.go
token/methods.go
token/methods_test.go
token/set_rate_test.go
token/token_test.go
token/transfer.go
token/vt_test_token.go

Tokens test migrated to MockStub usage

Tokens test

---

test/unit/allowed_balances_test.go
test/unit/external_locks_test.go
test/unit/external_transfers_test.go
test/unit/indexer_test.go
test/unit/industrial_balances_test.go
test/unit/key_types_signature_test.go
test/unit/metadata_test.go
test/unit/token_balances_test.go

Token balances test migrated to MockStub

Token balances test

---

token/buy_buyback.go
token/buy_buyback_test.go
token/common_test.go
token/errors.go
token/token_test.go
token/transfer.go
token/transfer_test.go

buy/buyback test migrated to MockStub usage

buy/buyback test migrated to MockStub usage

---

mocks/multisigned_user.go
mocks/user.go
token/get_fee_transfer_test.go

get-fee-transfer-test  migrated to MockStub usage

get-fee-transfer-test 
